function elementById<T extends HTMLElement>(id: string): T {
  const node = document.getElementById(id);
  if (!node) {
    throw new Error(`Missing dashboard element: ${id}`);
  }
  return node as T;
}

const ui = {
  sidebarToggle: elementById<HTMLButtonElement>('sidebar-toggle'),
  pageTitle: elementById<HTMLElement>('page-title'),
  pageSubtitle: elementById<HTMLElement>('page-subtitle'),
  viewGuide: elementById<HTMLElement>('view-guide'),
  topbar: elementById<HTMLElement>('page-title').closest('.topbar') as HTMLElement,
  nav: elementById<HTMLElement>('nav'),
  apiSearch: elementById<HTMLInputElement>('api-search'),
  apiStatusFilter: elementById<HTMLSelectElement>('api-status-filter'),
  apiList: elementById<HTMLElement>('api-list'),
  logoutButton: elementById<HTMLButtonElement>('logout-button'),
  themeSelect: elementById<HTMLSelectElement>('theme-select'),
  settingsSecurity: elementById<HTMLElement>('settings-security'),
  settingsLicense: elementById<HTMLElement>('settings-license'),
  overviewMetrics: elementById<HTMLElement>('overview-metrics'),
  overviewCharts: elementById<HTMLElement>('overview-charts'),
  exportOverviewJson: elementById<HTMLButtonElement>('export-overview-json'),
  exportOverviewReport: elementById<HTMLButtonElement>('export-overview-report'),
  exportOverviewHtml: elementById<HTMLButtonElement>('export-overview-html'),
  overviewAttention: elementById<HTMLElement>('overview-attention'),
  poPlaybookContent: elementById<HTMLElement>('po-playbook-content'),
  poActionWorkflow: elementById<HTMLButtonElement>('po-action-workflow'),
  poActionValidation: elementById<HTMLButtonElement>('po-action-validation'),
  poActionChecks: elementById<HTMLButtonElement>('po-action-checks'),
  poActionBaseline: elementById<HTMLButtonElement>('po-action-baseline'),
  poActionHealth: elementById<HTMLButtonElement>('po-action-health'),
  poActionReport: elementById<HTMLButtonElement>('po-action-report'),
  projectRegisterName: elementById<HTMLInputElement>('project-register-name'),
  projectRegisterAuthAdvanced: elementById<HTMLDetailsElement>('project-register-auth-advanced'),
  projectRegisterUser: elementById<HTMLInputElement>('project-register-user'),
  projectRegisterPass: elementById<HTMLInputElement>('project-register-pass'),
  projectRegisterWriteEnv: elementById<HTMLInputElement>('project-register-write-env'),
  projectRegisterButton: elementById<HTMLButtonElement>('project-register-button'),
  projectAddName: elementById<HTMLInputElement>('project-add-name'),
  projectAddAdvanced: elementById<HTMLDetailsElement>('project-add-advanced'),
  projectAddRoot: elementById<HTMLInputElement>('project-add-root'),
  projectAddDbPath: elementById<HTMLInputElement>('project-add-db-path'),
  projectAddButton: elementById<HTMLButtonElement>('project-add-button'),
  projectActiveSelect: elementById<HTMLSelectElement>('project-active-select'),
  projectSelectButton: elementById<HTMLButtonElement>('project-select-button'),
  projectLifecycleAdvanced: elementById<HTMLDetailsElement>('project-lifecycle-advanced'),
  projectDeleteConfirm: elementById<HTMLInputElement>('project-delete-confirm'),
  projectArchiveButton: elementById<HTMLButtonElement>('project-archive-button'),
  projectRestoreButton: elementById<HTMLButtonElement>('project-restore-button'),
  projectDeleteButton: elementById<HTMLButtonElement>('project-delete-button'),
  projectPolicyCadence: elementById<HTMLSelectElement>('project-policy-cadence'),
  projectPolicySchedule: elementById<HTMLInputElement>('project-policy-schedule'),
  projectPolicyBaselineMode: elementById<HTMLSelectElement>('project-policy-baseline-mode'),
  projectPolicyThreshold: elementById<HTMLInputElement>('project-policy-threshold'),
  projectPolicyBundleEnabled: elementById<HTMLInputElement>('project-policy-bundle-enabled'),
  projectPolicyBundleSchedule: elementById<HTMLInputElement>('project-policy-bundle-schedule'),
  projectPolicyBundleFormat: elementById<HTMLSelectElement>('project-policy-bundle-format'),
  projectPolicySaveButton: elementById<HTMLButtonElement>('project-policy-save-button'),
  projectPolicyApplyButton: elementById<HTMLButtonElement>('project-policy-apply-button'),
  projectRunBundleButton: elementById<HTMLButtonElement>('project-run-bundle-button'),
  projectBaselinePromoteButton: elementById<HTMLButtonElement>('project-baseline-promote-button'),
  projectHealthCheckButton: elementById<HTMLButtonElement>('project-health-check-button'),
  projectMonitorRefreshButton: elementById<HTMLButtonElement>('project-monitor-refresh-button'),
  projectReportDigestButton: elementById<HTMLButtonElement>('project-report-digest-button'),
  projectWorkflowFeedback: elementById<HTMLElement>('project-workflow-feedback'),
  projectWorkflowHealth: elementById<HTMLElement>('project-workflow-health'),
  projectWorkflowMonitor: elementById<HTMLElement>('project-workflow-monitor'),
  projectWorkflowRuns: elementById<HTMLElement>('project-workflow-runs'),
  projectWorkflowReport: elementById<HTMLElement>('project-workflow-report'),
  apiEmpty: elementById<HTMLElement>('api-empty'),
  apiWorkspace: elementById<HTMLElement>('api-workspace'),
  apiTitle: elementById<HTMLElement>('api-title'),
  apiSubtitle: elementById<HTMLElement>('api-subtitle'),
  checkNowButton: elementById<HTMLButtonElement>('check-now-button'),
  apiMethod: elementById<HTMLElement>('api-method'),
  apiPath: elementById<HTMLElement>('api-path'),
  apiMetaGrid: elementById<HTMLElement>('api-meta-grid'),
  apiKpis: elementById<HTMLElement>('api-kpis'),
  apiTrends: elementById<HTMLElement>('api-trends'),
  apiIncidentHistory: elementById<HTMLElement>('api-incident-history'),
  apiRunTable: elementById<HTMLElement>('api-run-table'),
  apiCoreInsight: elementById<HTMLElement>('api-core-insight'),
  fieldRoleGrid: elementById<HTMLElement>('field-role-grid'),
  poModeToggle: elementById<HTMLInputElement>('po-mode-toggle'),
  // Advanced tolerance controls (inside the collapsed Advanced section)
  configActiveTolerance: elementById<HTMLSelectElement>('config-active-tolerance'),
  configRelaxed: elementById<HTMLInputElement>('config-relaxed'),
  configNormal: elementById<HTMLInputElement>('config-normal'),
  configStrict: elementById<HTMLInputElement>('config-strict'),
  configReferences: elementById<HTMLTextAreaElement>('config-references'),
  configFeedback: elementById<HTMLElement>('config-feedback'),
  // Simple tolerance input (PO-facing, primary path)
  configToleranceSimple: elementById<HTMLInputElement>('config-tolerance-simple'),
  uploadFile: elementById<HTMLInputElement>('upload-file'),
  uploadButton: elementById<HTMLButtonElement>('upload-button'),
  uploadFeedback: elementById<HTMLElement>('upload-feedback'),
  uploadActivity: elementById<HTMLElement>('upload-activity'),
  configFooter: elementById<HTMLElement>('config-footer'),
  summaryFooter: elementById<HTMLElement>('summary-footer'),
  uploadsFooter: elementById<HTMLElement>('uploads-footer'),
  uploadPreviewStep: elementById<HTMLElement>('upload-preview-step'),
  uploadPreviewBody: elementById<HTMLElement>('upload-preview-body'),
  uploadConfirmToolbar: elementById<HTMLElement>('upload-confirm-toolbar'),
  previewUploadButton: elementById<HTMLButtonElement>('preview-upload-button'),
  cancelUploadButton: elementById<HTMLButtonElement>('cancel-upload-button'),
  exportUploads: elementById<HTMLButtonElement>('export-uploads'),
  // Template download links (in Upload guide and in API header)
  templateCsvLink: elementById<HTMLAnchorElement>('template-csv-link'),
  templateXlsxLink: elementById<HTMLAnchorElement>('template-xlsx-link'),
  templateCsvLinkUpload: elementById<HTMLAnchorElement>('template-csv-link-upload'),
  templateXlsxLinkUpload: elementById<HTMLAnchorElement>('template-xlsx-link-upload'),
  incidentsList: elementById<HTMLElement>('incidents-list'),
  errorsList: elementById<HTMLElement>('errors-list'),
  errorSearch: elementById<HTMLInputElement>('error-search'),
  errorStatusFilter: elementById<HTMLSelectElement>('error-status-filter'),
  errorCategoryFilter: elementById<HTMLSelectElement>('error-category-filter'),
  errorSeverityFilter: elementById<HTMLSelectElement>('error-severity-filter'),
  exportErrorsJson: elementById<HTMLButtonElement>('export-errors-json'),
  exportErrorsReport: elementById<HTMLButtonElement>('export-errors-report'),
  incidentSort: elementById<HTMLSelectElement>('incident-sort'),
  incidentFilters: elementById<HTMLElement>('incident-filters'),
  exportIncidents: elementById<HTMLButtonElement>('export-incidents'),
  exportIncidentsJson: elementById<HTMLButtonElement>('export-incidents-json'),
  exportIncidentsReport: elementById<HTMLButtonElement>('export-incidents-report'),
  exportIncidentsHtml: elementById<HTMLButtonElement>('export-incidents-html'),
  bulkAction: elementById<HTMLSelectElement>('bulk-action'),
  bulkNote: elementById<HTMLInputElement>('bulk-note'),
  bulkRun: elementById<HTMLButtonElement>('bulk-run'),
  bulkPreview: elementById<HTMLElement>('bulk-preview'),
  schedulerList: elementById<HTMLElement>('scheduler-list'),
  exportRuns: elementById<HTMLButtonElement>('export-runs'),
  exportRunsJson: elementById<HTMLButtonElement>('export-runs-json'),
  exportApiReport: elementById<HTMLButtonElement>('export-api-report'),
  exportApiHtml: elementById<HTMLButtonElement>('export-api-html'),
  densitySelect: elementById<HTMLSelectElement>('density-select'),
  defaultViewSelect: elementById<HTMLSelectElement>('default-view-select'),
  namedViewInput: elementById<HTMLInputElement>('named-view-input'),
  saveNamedView: elementById<HTMLButtonElement>('save-named-view'),
  exportNamedViews: elementById<HTMLButtonElement>('export-named-views'),
  importNamedViewsButton: elementById<HTMLButtonElement>('import-named-views-button'),
  importNamedViewsFile: elementById<HTMLInputElement>('import-named-views-file'),
  savedViews: elementById<HTMLElement>('saved-views'),
  drawerBackdrop: elementById<HTMLElement>('incident-drawer-backdrop'),
  drawer: elementById<HTMLElement>('incident-drawer'),
  drawerTitle: elementById<HTMLElement>('drawer-title'),
  drawerBody: elementById<HTMLElement>('drawer-body'),
  drawerClose: elementById<HTMLButtonElement>('drawer-close'),
  confirmBackdrop: elementById<HTMLElement>('confirm-backdrop'),
  confirmModal: elementById<HTMLElement>('confirm-modal'),
  confirmTitle: elementById<HTMLElement>('confirm-title'),
  confirmCopy: elementById<HTMLElement>('confirm-copy'),
  confirmCancel: elementById<HTMLButtonElement>('confirm-cancel'),
  confirmAccept: elementById<HTMLButtonElement>('confirm-accept'),
  toastStack: elementById<HTMLElement>('toast-stack'),
  reportEndpointSelect: elementById<HTMLSelectElement>('report-endpoint-select'),
  reportGrainSearch: elementById<HTMLInputElement>('report-grain-search'),
  runReportButton: elementById<HTMLButtonElement>('run-report-button'),
  reportsFeedback: elementById<HTMLElement>('reports-feedback'),
  reportsContent: elementById<HTMLElement>('reports-content'),
  exportReportCsv: elementById<HTMLButtonElement>('export-report-csv'),
  incidentsFeedback: elementById<HTMLElement>('incidents-feedback'),
  // Run Detail Drawer
  runDetailDrawer: elementById<HTMLElement>('run-detail-drawer'),
  runDetailTitle: elementById<HTMLElement>('run-detail-title'),
  runDetailContent: elementById<HTMLElement>('run-detail-content'),
  runDetailClose: elementById<HTMLButtonElement>('run-detail-close'),
};

export { ui };
